version: "3.9"  # optional since v1.27.0
services:
  app:
      build:
        context: .
      ports:
        - 8020:8020
      volumes:
        - ./app:/app
      depends_on:
        - db
        - redis
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6378:6379