"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

from decouple import config
from django.conf.global_settings import DATETIME_INPUT_FORMATS

from .installedapps import INSTALLED_APPS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PLATFORM_NAME = config('PLATFORM_NAME', default='Gwent Groups')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/
INSTALLED_APPS = INSTALLED_APPS
DEBUG = config("CMS_DEBUG", cast=bool, default=False)
SECURE_HSTS_SECONDS = config("CMS_SECURE_HSTS_SECONDS", cast=int, default=0)
SECURE_SSL_REDIRECT = config("CMS_SECURE_SSL_REDIRECT", cast=bool, )
SESSION_COOKIE_SECURE = config("CMS_SESSION_COOKIE_SECURE", cast=bool)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config("CMS_SECURE_HSTS_INCLUDE_SUBDOMAINS")
SECURE_HSTS_PRELOAD = config("CMS_SECURE_HSTS_PRELOAD", cast=bool)
CSRF_COOKIE_SECURE = config("CMS_CSRF_COOKIE_SECURE", cast=bool)

ALLOWED_HOSTS = config("CMS_ALLOWED_HOSTS", cast=str).split(',')
SECRET_KEY = config("CMS_SECRET_KEY")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': config('POSTGRES_DB_HOST'),
        'NAME': config('POSTGRES_DB_NAME'),
        'USER': config('POSTGRES_DB_USER'),
        'PASSWORD': config('POSTGRES_DB_PASS'),
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": config('REDIS_HOST'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": config("REDIS_ENV_PREFIX")
    }
}

# CELERY STUFF

CELERY_BROKER_URL = config('REDIS_BROKER_URL')
CELERY_RESULT_BACKEND = config('REDIS_BROKER_URL')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/London'
MY_CELERY_APP = 'app.celery'

CELERY_BEAT_SCHEDULE = {
    'send-event-reminders': {
        'task': 'groups.tasks.reminder',
        'schedule': 60.0,
        'args': ()
    },
}
# CELERY END

# EMAIL
EMAIL_DEFAULT_ADDRESS = config("EMAIL_DEFAULT_ADDRESS")
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default="True", cast=bool)
# EMAIL END


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'GMT'

USE_I18N = True

USE_L10N = False

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

CRISPY_TEMPLATE_PACK = 'bootstrap4'

DATETIME_FORMAT = "d/m/Y H:i"
DATETIME_INPUT_FORMATS += ('%d/%m/%Y %H:%M',)

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(__file__), 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'

AUTH_USER_MODEL = 'accounts.MCCUser'

TEST_RUNNER = 'app.runner.PytestTestRunner'

MJML_EXEC_CMD = config("MJML_EXEC_CMD_PATH", default=os.path.join(BASE_DIR, '../node_modules/.bin/mjml'))
MJML_EXEC_CMD_ARGS = [MJML_EXEC_CMD, '--minify']
