# Generated by Django 3.2.8 on 2021-11-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
