# Generated by Django 3.2.8 on 2021-11-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
