# Generated by Django 3.2.8 on 2021-11-29 14:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('comms', '0003_alter_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='body',
        ),
        migrations.AddField(
            model_name='email',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
