# Generated by Django 3.2.8 on 2021-11-29 14:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('comms', '0004_auto_20211129_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='mjml_template',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
