# Generated by Django 3.2.8 on 2021-12-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0005_auto_20211129_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='dispatch_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
