# Generated by Django 3.2.8 on 2021-10-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='slug',
            field=models.SlugField(),
        ),
    ]
