# Generated by Django 3.2.8 on 2021-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendees', '0002_alter_attendee_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
