# Generated by Django 3.2.8 on 2021-10-20 10:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('attendees', '0003_alter_attendee_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='slug',
        ),
        migrations.AddField(
            model_name='attendee',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
