# Generated by Django 3.2.8 on 2021-11-30 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('attendees', '0004_auto_20211020_1057'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=75)),
                ('provider', models.CharField(blank=True, max_length=75, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('READING', 'Reading'), ('CYCLING', 'Cycling'),
                                                                   ('CINEMA', 'Cinema'), ('GAMING', 'Gaming'),
                                                                   ('TECH', 'Tech'), ('CHESS', 'Chess'),
                                                                   ('CHATTING', 'Chatting'),
                                                                   ('EDUCATIONAL', 'Educational')], max_length=50,
                                              null=True)),
                ('active', models.BooleanField(default=True)),
                ('public_contact', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=100)),
                ('admin',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
                'unique_together': {('name', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, default=None, null=True)),
                ('join_url', models.URLField()),
                ('location', models.CharField(max_length=50)),
                ('perpetual', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(related_name='attendees', to='attendees.Attendee')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term',
                                            to='groups.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, default=None, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event',
                                           to='groups.term')),
            ],
            options={
                'ordering': ['end_time'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_deleted', models.DateField(blank=True, default=None, null=True)),
                ('inactive', models.BooleanField(default=False)),
                ('proposer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_proposer',
                                   to='attendees.attendee')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_term',
                                           to='groups.term')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
