# Generated by Django 3.2.8 on 2021-11-30 15:03

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
