# Generated by Django 3.2.8 on 2021-12-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0004_auto_20211020_1057'),
        ('groups', '0002_auto_20211130_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='attendees.Attendee'),
        ),
    ]
