# Generated by Django 3.2.8 on 2021-12-08 17:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('groups', '0003_alter_term_attendees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterField(
            model_name='group',
            name='public_contact',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
